In [4]:
# import numpy library
import numpy as np

In [7]:
# create a 1 dimensional array
array_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:\n", array_1d)

1D Array:
 [10 20 30 40 50]


In [8]:
# create a 2 dimensional array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [15]:
# get the shape of the 2D array
print("Shape of 2D Array:", array_2d.shape) # Output: (2, 3) which means 2 rows and 3 columns

Shape of 2D Array: (2, 3)


In [16]:
# accessing elements using indexing
print("Element at (0,1):", array_2d[0, 1])  # Output: 2 because indexing starts at 0

Element at (0,1): 2


In [17]:
# sum of 2 arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
c = a + b
print("Sum of arrays a and b:", c)  # Output: [5 7 9]

Sum of arrays a and b: [5 7 9]


In [19]:
# sum of 2 arrays using .add() function
d = np.add(a, b)
print("Sum of arrays a and b using np.add():", d)  # Output: [5 7 9]

Sum of arrays a and b using np.add(): [5 7 9]


In [21]:
# multiplication of 2 2d arrays
e = np.array([[1, 2], [3, 4]]) 
f = np.array([[5, 6], [7, 8]])
g = np.dot(e, f)
print("Dot product of arrays e and f:\n", g)  # Output: [[19 22] [43 50]]

Dot product of arrays e and f:
 [[19 22]
 [43 50]]


In [23]:
# other dot product method
h = e @ f
print("Dot product of arrays e and f using @ operator:\n", h)  # Output: [[19 22] [43 50]]

Dot product of arrays e and f using @ operator:
 [[19 22]
 [43 50]]
