In [1]:
# import numpy library
import numpy as np

In [2]:
# create a 1 dimensional array
array_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:\n", array_1d)

1D Array:
 [10 20 30 40 50]


In [3]:
# create a 2 dimensional array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# get the shape of the 2D array
print("Shape of 2D Array:", array_2d.shape) # Output: (2, 3) which means 2 rows and 3 columns

Shape of 2D Array: (2, 3)


In [5]:
# accessing elements using indexing
print("Element at (0,1):", array_2d[0, 1])  # Output: 2 because indexing starts at 0

Element at (0,1): 2


In [6]:
# sum of 2 arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
c = a + b
print("Sum of arrays a and b:", c)  # Output: [5 7 9]

Sum of arrays a and b: [5 7 9]


In [7]:
# sum of 2 arrays using .add() function
d = np.add(a, b)
print("Sum of arrays a and b using np.add():", d)  # Output: [5 7 9]

Sum of arrays a and b using np.add(): [5 7 9]


In [8]:
# multiplication of 2 2d arrays
e = np.array([[1, 2], [3, 4]]) 
f = np.array([[5, 6], [7, 8]])
g = np.dot(e, f)
print("Dot product of arrays e and f:\n", g)  # Output: [[19 22] [43 50]]

Dot product of arrays e and f:
 [[19 22]
 [43 50]]


In [9]:
# other dot product method
h = e @ f
print("Dot product of arrays e and f using @ operator:\n", h)  # Output: [[19 22] [43 50]]

Dot product of arrays e and f using @ operator:
 [[19 22]
 [43 50]]


## NumPy matrix operations, compute rank, verify null space

### Exercise 1 – Basic matrix creation and shapes
1. Create the following matrices in NumPy:

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 0], [0 ,1], [1, -1]])
c = np.array([[2, -1, 0], [0, 3, 1], [4, 1, -2]])

In [11]:
# print the arrays
print("Array a:\n", a)  # Output: [[1 2 3] [4 5 6]]
print("Array b:\n", b)  # Output: [[1 0] [0 1] [1 -1]]
print("Array c:\n", c)  # Output: [[2 -1 0] [0 3 1] [4 1 -2]]

Array a:
 [[1 2 3]
 [4 5 6]]
Array b:
 [[ 1  0]
 [ 0  1]
 [ 1 -1]]
Array c:
 [[ 2 -1  0]
 [ 0  3  1]
 [ 4  1 -2]]


2. Verify their shape, ndim, and dtype using NumPy.

In [12]:
# get the data type, number of dimensions and shape of array a
print("Data type of array a:", a.dtype)
print("Number of dimensions of array a:", a.ndim)
print("Shape of array a:", a.shape) 

# get the data type, number of dimensions and shape of array b
print("----------------------------------")
print("Data type of array b:", b.dtype)
print("Number of dimensions of array b:", b.ndim)
print("Shape of array b:", b.shape)

# get the data type, number of dimensions and shape of array c
print("----------------------------------")
print("Data type of array c:", c.dtype)
print("Number of dimensions of array c:", c.ndim)   
print("Shape of array c:", c.shape)

Data type of array a: int64
Number of dimensions of array a: 2
Shape of array a: (2, 3)
----------------------------------
Data type of array b: int64
Number of dimensions of array b: 2
Shape of array b: (3, 2)
----------------------------------
Data type of array c: int64
Number of dimensions of array c: 2
Shape of array c: (3, 3)


In [13]:
a_transpose = a.T
print("array a:\n", a)  # Output: [[1 2 3] [4 5 6]]
print("Transpose of array a:\n", a_transpose)  # Output: [[1 4] [2 5] [3 6]]

b_transpose = b.T
print("-------------------------------")
print("array b:\n", b)  # Output: [[1 0] [0 1] [1 -1]]
print("Transpose of array b:\n", b_transpose)  # Output: [[1 0 1] [0 1 -1]]

array a:
 [[1 2 3]
 [4 5 6]]
Transpose of array a:
 [[1 4]
 [2 5]
 [3 6]]
-------------------------------
array b:
 [[ 1  0]
 [ 0  1]
 [ 1 -1]]
Transpose of array b:
 [[ 1  0  1]
 [ 0  1 -1]]


In [14]:
# matrix multiplication of a and b
result_ab = np.dot(a, b)  
print("Matrix multiplication of a and b:\n", result_ab)  # Output: [[4 1] [10 1]]

# matrix multiplication of a_transpose and b_transpose
result_ab_transpose = np.dot(a_transpose, b_transpose)
print("Matrix multiplication of a_transpose and b_transpose:\n", result_ab_transpose)  # Output: [[4 1] [10 1]]

Matrix multiplication of a and b:
 [[ 4 -1]
 [10 -1]]
Matrix multiplication of a_transpose and b_transpose:
 [[ 1  4 -3]
 [ 2  5 -3]
 [ 3  6 -3]]


In [16]:
# check if (a·b)ᵀ = bᵀ·aᵀ using the property: (A·B)ᵀ = Bᵀ·Aᵀ
result_b_transpose_a_transpose = np.dot(b_transpose, a_transpose)
print("Matrix multiplication of b_transpose and a_transpose:\n", result_b_transpose_a_transpose)

# Transpose of a·b
result_ab_transpose = result_ab.T
print("Transpose of the dot product of a and b:\n", result_ab_transpose)

# check if (a·b)ᵀ equals bᵀ·aᵀ using np.allclose() function
is_equal = np.allclose(result_ab_transpose, result_b_transpose_a_transpose)    
print("Is (a·b)ᵀ equal to b_transpose·a_transpose?", is_equal)  # Output: True

Matrix multiplication of b_transpose and a_transpose:
 [[ 4 10]
 [-1 -1]]
Transpose of the dot product of a and b:
 [[ 4 10]
 [-1 -1]]
Is (a·b)ᵀ equal to b_transpose·a_transpose? True


### Exercise 2 – Ranks of small matrices
1. For each matrix below, compute its rank using np.linalg.matrix_rank:

In [19]:
m1 = np.array([[1, 2], [2, 4]])
m2 = np.array([[1 ,2 ,3], [0, 1, 2], [0, 0, 0]])
m3 = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 2]])

print("Matrix m1:\n", m1)  # Output: [[1 2] [2 4]]
print("--------------------------------")
print("Matrix m2:\n", m2)  # Output: [[1 2 3] [0 1 2] [0 0 0]]
print("--------------------------------")
print("Matrix m3:\n", m3)  # Output: [[1 0 1] [0 1 1] [1 1 2]]

Matrix m1:
 [[1 2]
 [2 4]]
--------------------------------
Matrix m2:
 [[1 2 3]
 [0 1 2]
 [0 0 0]]
--------------------------------
Matrix m3:
 [[1 0 1]
 [0 1 1]
 [1 1 2]]


In [20]:
# compute the rank of the matrices using np.linalg.matrix_rank() function
rank_m1 = np.linalg.matrix_rank(m1)
rank_m2 = np.linalg.matrix_rank(m2)
rank_m3 = np.linalg.matrix_rank(m3)

print("Rank of matrix m1:", rank_m1)
print("Rank of matrix m2:", rank_m2)
print("Rank of matrix m3:", rank_m3)

Rank of matrix m1: 1
Rank of matrix m2: 2
Rank of matrix m3: 2


### Exercise 3 – Rank and null space dimension

In [23]:
n = np.array([[1, 2, 3, 4], [2, 4, 6, 8], [1, 1, 1, 1]])
print("Matrix n:\n", n)  # Output: [[1 2 3 4] [2 4 6 8] [1 1 1 1]]

Matrix n:
 [[1 2 3 4]
 [2 4 6 8]
 [1 1 1 1]]


In [22]:
# compute the rank of the matrice n
rank_n = np.linalg.matrix_rank(n)
print("Rank of matrix n:", rank_n)

Rank of matrix n: 2


In [27]:
# compute the number of columns of matrix n
num_columns_n = n.shape[1]
print("Number of columns in matrix n:", num_columns_n)

Number of columns in matrix n: 4


In [ ]:
# compute the dimension of the null space of matrix n
null_space_dimension_n = n.shape[1] - rank_n
print("Dimension of the null space of matrix n:", null_space_dimension_n)

Dimension of the null space of matrix n: 2


In [30]:
p = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
print("Matrix p:\n", p)  # Output: [[1 2 3] [2 4 6] [3 6 9]]   

Matrix p:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [31]:
# Compute u, s, vh = np.linalg.svd(P)
u, s, vh = np.linalg.svd(p)
print("Matrix u:\n", u)

Matrix u:
 [[-0.26726124  0.95547204  0.12507841]
 [-0.53452248 -0.03899557 -0.84425414]
 [-0.80178373 -0.29249363  0.52114329]]


In [36]:
# print the singular values approximate to 4 decimal places
s_rounded = np.round(s, 4)
print("Singular values of matrix p:", s_rounded)

Singular values of matrix p: [14.  0.  0.]


---
## NumPy: Inverses & Determinants	
Solve linear systems using  NumPy np.linalg.det, np.linalg.inv

In [16]:
# find the inverse of a 2x2 matrix 
# exercise 1

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)

# create a 2x2 matrix
matrix_2x2 = np.array([[-9, -6], [0, 2]])
# compute the determinant of the 2x2 matrix
det_matrix_2x2 = np.linalg.det(matrix_2x2)
print("Determinant of the 2x2 matrix:", det_matrix_2x2)
# check if the determinant is not zero before computing the inverse
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: -18.000000000000004
Inverse of the 2x2 matrix:
 [[-1/9 -1/3]
 [0 1/2]]


In [17]:
# find the inverse of a 2x2 matrix 
# exercise 2

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)
matrix_2x2 = np.array([[-4, 2], [-6, 6]])
det_matrix_2x2 = np.linalg.det(matrix_2x2)
print("Determinant of the 2x2 matrix:", det_matrix_2x2)
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: -12.0
Inverse of the 2x2 matrix:
 [[-1/2 1/6]
 [-1/2 1/3]]


In [18]:
# find the inverse of a 2x2 matrix 
# exercise 

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)
matrix_2x2 = np.array([[-7, 0], [-6, 3]])
det_matrix_2x2 = np.linalg.det(matrix_2x2)
print("Determinant of the 2x2 matrix:", det_matrix_2x2)
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: -21.0
Inverse of the 2x2 matrix:
 [[-1/7 0]
 [-2/7 1/3]]


In [19]:
# find the inverse of a 2x2 matrix 
# exercise 4

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)

matrix_2x2 = np.array([[1, 4], [4, 9]])
det_matrix_2x2 = np.linalg.det(matrix_2x2)

print("Determinant of the 2x2 matrix:", det_matrix_2x2)
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: -6.999999999999999
Inverse of the 2x2 matrix:
 [[-9/7 4/7]
 [4/7 -1/7]]


In [ ]:
# find the inverse of a 2x2 matrix 
# exercise 5

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)

matrix_2x2 = np.array([[-10, 1], [2, -1]])
det_matrix_2x2 = np.linalg.det(matrix_2x2)

print("Determinant of the 2x2 matrix:", det_matrix_2x2)
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")