In [1]:
# import numpy library
import numpy as np

In [2]:
# create a 1 dimensional array
array_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:\n", array_1d)

1D Array:
 [10 20 30 40 50]


In [3]:
# create a 2 dimensional array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# get the shape of the 2D array
print("Shape of 2D Array:", array_2d.shape) # Output: (2, 3) which means 2 rows and 3 columns

Shape of 2D Array: (2, 3)


In [5]:
# accessing elements using indexing
print("Element at (0,1):", array_2d[0, 1])  # Output: 2 because indexing starts at 0

Element at (0,1): 2


In [6]:
# sum of 2 arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
c = a + b
print("Sum of arrays a and b:", c)  # Output: [5 7 9]

Sum of arrays a and b: [5 7 9]


In [7]:
# sum of 2 arrays using .add() function
d = np.add(a, b)
print("Sum of arrays a and b using np.add():", d)  # Output: [5 7 9]

Sum of arrays a and b using np.add(): [5 7 9]


In [8]:
# multiplication of 2 2d arrays
e = np.array([[1, 2], [3, 4]]) 
f = np.array([[5, 6], [7, 8]])
g = np.dot(e, f)
print("Dot product of arrays e and f:\n", g)  # Output: [[19 22] [43 50]]

Dot product of arrays e and f:
 [[19 22]
 [43 50]]


In [9]:
# other dot product method
h = e @ f
print("Dot product of arrays e and f using @ operator:\n", h)  # Output: [[19 22] [43 50]]

Dot product of arrays e and f using @ operator:
 [[19 22]
 [43 50]]


## NumPy matrix operations, compute rank, verify null space

### Exercise 1 – Basic matrix creation and shapes
1. Create the following matrices in NumPy:

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 0], [0 ,1], [1, -1]])
c = np.array([[2, -1, 0], [0, 3, 1], [4, 1, -2]])

In [11]:
# print the arrays
print("Array a:\n", a)  # Output: [[1 2 3] [4 5 6]]
print("Array b:\n", b)  # Output: [[1 0] [0 1] [1 -1]]
print("Array c:\n", c)  # Output: [[2 -1 0] [0 3 1] [4 1 -2]]

Array a:
 [[1 2 3]
 [4 5 6]]
Array b:
 [[ 1  0]
 [ 0  1]
 [ 1 -1]]
Array c:
 [[ 2 -1  0]
 [ 0  3  1]
 [ 4  1 -2]]


2. Verify their shape, ndim, and dtype using NumPy.

In [12]:
# get the data type, number of dimensions and shape of array a
print("Data type of array a:", a.dtype)
print("Number of dimensions of array a:", a.ndim)
print("Shape of array a:", a.shape) 

# get the data type, number of dimensions and shape of array b
print("----------------------------------")
print("Data type of array b:", b.dtype)
print("Number of dimensions of array b:", b.ndim)
print("Shape of array b:", b.shape)

# get the data type, number of dimensions and shape of array c
print("----------------------------------")
print("Data type of array c:", c.dtype)
print("Number of dimensions of array c:", c.ndim)   
print("Shape of array c:", c.shape)

Data type of array a: int64
Number of dimensions of array a: 2
Shape of array a: (2, 3)
----------------------------------
Data type of array b: int64
Number of dimensions of array b: 2
Shape of array b: (3, 2)
----------------------------------
Data type of array c: int64
Number of dimensions of array c: 2
Shape of array c: (3, 3)


In [13]:
a_transpose = a.T
print("array a:\n", a)  # Output: [[1 2 3] [4 5 6]]
print("Transpose of array a:\n", a_transpose)  # Output: [[1 4] [2 5] [3 6]]

b_transpose = b.T
print("-------------------------------")
print("array b:\n", b)  # Output: [[1 0] [0 1] [1 -1]]
print("Transpose of array b:\n", b_transpose)  # Output: [[1 0 1] [0 1 -1]]

array a:
 [[1 2 3]
 [4 5 6]]
Transpose of array a:
 [[1 4]
 [2 5]
 [3 6]]
-------------------------------
array b:
 [[ 1  0]
 [ 0  1]
 [ 1 -1]]
Transpose of array b:
 [[ 1  0  1]
 [ 0  1 -1]]


In [14]:
# matrix multiplication of a and b
result_ab = np.dot(a, b)  
print("Matrix multiplication of a and b:\n", result_ab)  # Output: [[4 1] [10 1]]

# matrix multiplication of a_transpose and b_transpose
result_ab_transpose = np.dot(a_transpose, b_transpose)
print("Matrix multiplication of a_transpose and b_transpose:\n", result_ab_transpose)  # Output: [[4 1] [10 1]]

Matrix multiplication of a and b:
 [[ 4 -1]
 [10 -1]]
Matrix multiplication of a_transpose and b_transpose:
 [[ 1  4 -3]
 [ 2  5 -3]
 [ 3  6 -3]]


In [16]:
# check if (a·b)ᵀ = bᵀ·aᵀ using the property: (A·B)ᵀ = Bᵀ·Aᵀ
result_b_transpose_a_transpose = np.dot(b_transpose, a_transpose)
print("Matrix multiplication of b_transpose and a_transpose:\n", result_b_transpose_a_transpose)

# Transpose of a·b
result_ab_transpose = result_ab.T
print("Transpose of the dot product of a and b:\n", result_ab_transpose)

# check if (a·b)ᵀ equals bᵀ·aᵀ using np.allclose() function
is_equal = np.allclose(result_ab_transpose, result_b_transpose_a_transpose)    
print("Is (a·b)ᵀ equal to b_transpose·a_transpose?", is_equal)  # Output: True

Matrix multiplication of b_transpose and a_transpose:
 [[ 4 10]
 [-1 -1]]
Transpose of the dot product of a and b:
 [[ 4 10]
 [-1 -1]]
Is (a·b)ᵀ equal to b_transpose·a_transpose? True


### Exercise 2 – Ranks of small matrices
1. For each matrix below, compute its rank using np.linalg.matrix_rank:

In [19]:
m1 = np.array([[1, 2], [2, 4]])
m2 = np.array([[1 ,2 ,3], [0, 1, 2], [0, 0, 0]])
m3 = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 2]])

print("Matrix m1:\n", m1)  # Output: [[1 2] [2 4]]
print("--------------------------------")
print("Matrix m2:\n", m2)  # Output: [[1 2 3] [0 1 2] [0 0 0]]
print("--------------------------------")
print("Matrix m3:\n", m3)  # Output: [[1 0 1] [0 1 1] [1 1 2]]

Matrix m1:
 [[1 2]
 [2 4]]
--------------------------------
Matrix m2:
 [[1 2 3]
 [0 1 2]
 [0 0 0]]
--------------------------------
Matrix m3:
 [[1 0 1]
 [0 1 1]
 [1 1 2]]


In [20]:
# compute the rank of the matrices using np.linalg.matrix_rank() function
rank_m1 = np.linalg.matrix_rank(m1)
rank_m2 = np.linalg.matrix_rank(m2)
rank_m3 = np.linalg.matrix_rank(m3)

print("Rank of matrix m1:", rank_m1)
print("Rank of matrix m2:", rank_m2)
print("Rank of matrix m3:", rank_m3)

Rank of matrix m1: 1
Rank of matrix m2: 2
Rank of matrix m3: 2


### Exercise 3 – Rank and null space dimension

In [23]:
n = np.array([[1, 2, 3, 4], [2, 4, 6, 8], [1, 1, 1, 1]])
print("Matrix n:\n", n)  # Output: [[1 2 3 4] [2 4 6 8] [1 1 1 1]]

Matrix n:
 [[1 2 3 4]
 [2 4 6 8]
 [1 1 1 1]]


In [22]:
# compute the rank of the matrice n
rank_n = np.linalg.matrix_rank(n)
print("Rank of matrix n:", rank_n)

Rank of matrix n: 2


In [27]:
# compute the number of columns of matrix n
num_columns_n = n.shape[1]
print("Number of columns in matrix n:", num_columns_n)

Number of columns in matrix n: 4


In [ ]:
# compute the dimension of the null space of matrix n
null_space_dimension_n = n.shape[1] - rank_n
print("Dimension of the null space of matrix n:", null_space_dimension_n)

Dimension of the null space of matrix n: 2


In [30]:
p = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
print("Matrix p:\n", p)  # Output: [[1 2 3] [2 4 6] [3 6 9]]   

Matrix p:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [31]:
# Compute u, s, vh = np.linalg.svd(P)
u, s, vh = np.linalg.svd(p)
print("Matrix u:\n", u)

Matrix u:
 [[-0.26726124  0.95547204  0.12507841]
 [-0.53452248 -0.03899557 -0.84425414]
 [-0.80178373 -0.29249363  0.52114329]]


In [36]:
# print the singular values approximate to 4 decimal places
s_rounded = np.round(s, 4)
print("Singular values of matrix p:", s_rounded)

Singular values of matrix p: [14.  0.  0.]


---
## NumPy: Inverses & Determinants	
Solve linear systems using  NumPy np.linalg.det, np.linalg.inv

In [16]:
# find the inverse of a 2x2 matrix 
# exercise 1

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)

# create a 2x2 matrix
matrix_2x2 = np.array([[-9, -6], [0, 2]])
# compute the determinant of the 2x2 matrix
det_matrix_2x2 = np.linalg.det(matrix_2x2)
print("Determinant of the 2x2 matrix:", det_matrix_2x2)
# check if the determinant is not zero before computing the inverse
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: -18.000000000000004
Inverse of the 2x2 matrix:
 [[-1/9 -1/3]
 [0 1/2]]


In [17]:
# find the inverse of a 2x2 matrix 
# exercise 2

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)
matrix_2x2 = np.array([[-4, 2], [-6, 6]])
det_matrix_2x2 = np.linalg.det(matrix_2x2)
print("Determinant of the 2x2 matrix:", det_matrix_2x2)
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: -12.0
Inverse of the 2x2 matrix:
 [[-1/2 1/6]
 [-1/2 1/3]]


In [18]:
# find the inverse of a 2x2 matrix 
# exercise 

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)
matrix_2x2 = np.array([[-7, 0], [-6, 3]])
det_matrix_2x2 = np.linalg.det(matrix_2x2)
print("Determinant of the 2x2 matrix:", det_matrix_2x2)
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: -21.0
Inverse of the 2x2 matrix:
 [[-1/7 0]
 [-2/7 1/3]]


In [19]:
# find the inverse of a 2x2 matrix 
# exercise 4

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)

matrix_2x2 = np.array([[1, 4], [4, 9]])
det_matrix_2x2 = np.linalg.det(matrix_2x2)

print("Determinant of the 2x2 matrix:", det_matrix_2x2)
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: -6.999999999999999
Inverse of the 2x2 matrix:
 [[-9/7 4/7]
 [4/7 -1/7]]


In [2]:
# find the inverse of a 2x2 matrix 
# exercise 5

# imnport the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)

matrix_2x2 = np.array([[-10, 1], [2, -1]])
det_matrix_2x2 = np.linalg.det(matrix_2x2)

print("Determinant of the 2x2 matrix:", det_matrix_2x2)
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: 8.000000000000002
Inverse of the 2x2 matrix:
 [[-1/8 -1/8]
 [-1/4 -5/4]]


---
## NumPy: Linear Systems	
Python Mini-Project: Linear Systems	Create Python script to solve linear systems

In [ ]:
# solve the system of equations using the inverse of the matrix
# import the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)

import numpy as np
matrix_2x2 = np.array([[6 ,2], [2, 4]])
b = np.array([[4], [4]])
det_matrix_2x2 = np.linalg.det(matrix_2x2)

print("Determinant of the 2x2 matrix:", det_matrix_2x2)
if det_matrix_2x2 != 0:
    inverse_matrix_2x2 = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix:\n", inverse_matrix_2x2)
else:
    print("The 2x2 matrix is singular and does not have an inverse.")

adj = det_matrix_2x2 * np.linalg.inv(matrix_2x2)
x = inverse_matrix_2x2 @ b
print("Solution x:\n", x)

Determinant of the 2x2 matrix: 20.000000000000007
Inverse of the 2x2 matrix:
 [[1/5 -1/10]
 [-1/10 3/10]]
Solution x:
 [[2/5]
 [4/5]]


In [19]:
# solve the system of equations using the inverse of the matrix
import numpy as np
matrix_3x3 = np.array([[17, 25, -10], [10, 15, -6], [-8, -12, 5]])
b = np.array([[3], [5], [-1]])
det_matrix_3x3 = np.linalg.det(matrix_3x3)

print("Determinant of the 3x3 matrix:", det_matrix_3x3)
if det_matrix_3x3 != 0:
    inverse_matrix_3x3 = np.linalg.inv(matrix_3x3)
    print("Inverse of the 3x3 matrix:\n", inverse_matrix_3x3)
else:
    print("The 3x3 matrix is singular and does not have an inverse.")

adj = det_matrix_3x3 * np.linalg.inv(matrix_3x3)
x = inverse_matrix_3x3 @ b
print("Solution x:\n", x)

Determinant of the 3x3 matrix: 0.9999999999999931
Inverse of the 3x3 matrix:
 [[3 -5 0]
 [-2 5 2]
 [0 4 5]]
Solution x:
 [[-16]
 [17]
 [15]]


 ## Create a program to solve the system of equations using the inverse of the matrix

In [ ]:
# create a program to solve the system of equations using the inverse of the matrix
# take as an input the coefficients of the variables and the constants of the equations, 
# then compute the inverse of the coefficient matrix and multiply it by the constants vector to find the solution.
# the program should be able to handle any number of equations and variables, as long as the coefficient matrix is square and invertible.

# import the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)

# set a random seed for reproducibility
seed = 42

# create random 2x2 matrix and 2x1 vector
n = 2
rng = np.random.default_rng(seed)

A = rng.integers(-10, 11, size=(n, n)).astype(float)
b = rng.integers(-10, 11, size=(n, 1)).astype(float)
print("Random 2x2 matrix A:\n", A)
print("Random 2x1 vector b:\n", b)

# compute the determinant of the coefficient matrix
det_A = np.linalg.det(A)
print("Determinant of the coefficient matrix A:", det_A)

if det_A != 0:
    # compute the inverse of the coefficient matrix
    A_inv = np.linalg.inv(A)
    print("Inverse of the coefficient matrix A:\n", A_inv)
    
    # compute the solution by multiplying the inverse of the coefficient matrix with the constants vector
    solution = A_inv @ b
    print("Solution of the system of equations:\n", solution)



Random 2x2 matrix A:
 [[-9 6]
 [3 -1]]
Random 2x1 vector b:
 [[-1]
 [8]]
Determinant of the coefficient matrix A: -9.000000000000002
Inverse of the coefficient matrix A:
 [[1/9 2/3]
 [1/3 1]]
Solution of the system of equations:
 [[47/9]
 [23/3]]


In [1]:
import numpy as np

def solve_random_systems(num_systems, n, seed, regenerate_singular):
    """
    Generate and solve `num_systems` random linear systems Ax = b
    where A is n x n and b is n x 1.

    Args:
      num_systems (int): how many systems to generate and solve.
      n (int): size of the square coefficient matrix.
      seed (int or None): RNG seed for reproducibility. None => random seed.
      regenerate_singular (bool): if True, regenerate A until invertible.
                                 if False, skip singular systems and report them.

    Returns:
      results (list of dict): each dict contains 'A', 'b', 'x', 'status', 'det' (if computed)
    """
    rng = np.random.default_rng(seed)
    results = []

    for i in range(num_systems):
        attempt = 0
        while True:
            attempt += 1
            # Example distribution: integers from -10..10
            A = rng.integers(-10, 11, size=(n, n)).astype(float)
            b = rng.integers(-10, 11, size=(n, 1)).astype(float)

            # determinant check (use isclose for float precision)
            detA = np.linalg.det(A)
            if not np.isclose(detA, 0.0):
                # solvable
                try:
                    x = np.linalg.solve(A, b)  # more stable than inv(A) @ b
                    results.append({'A': A, 'b': b, 'x': x, 'status': 'solved', 'det': detA})
                except np.linalg.LinAlgError as e:
                    # numerically unstable or singular despite det check
                    results.append({'A': A, 'b': b, 'x': None, 'status': f'error: {e}', 'det': detA})
                break
            else:
                # A is singular
                if regenerate_singular:
                    # try again (but avoid infinite loop: cap attempts)
                    if attempt >= 100:
                        results.append({'A': A, 'b': b, 'x': None, 'status': 'singular_after_retries', 'det': detA})
                        break
                    continue
                else:
                    results.append({'A': A, 'b': b, 'x': None, 'status': 'singular', 'det': detA})
                    break

    return results


if __name__ == "__main__":
    res = solve_random_systems(num_systems=2, n=2, seed=42, regenerate_singular=True)
    solved = sum(1 for r in res if r['status'] == 'solved')
    print(f"Solved {solved}/{len(res)} systems.\n")

    # Print first 5 solutions for inspection
    for i, r in enumerate(res[:5], start=1):
        print(f"--- System {i} ---")
        print("A =\n", r['A'])
        print("b =\n", r['b'].ravel())
        print("det(A) =", r['det'])
        print("x =\n", r['x'].ravel() if r['x'] is not None else None)
        print("status:", r['status'])
        print()

Solved 2/2 systems.

--- System 1 ---
A =
 [[-9.  6.]
 [ 3. -1.]]
b =
 [-1.  8.]
det(A) = -9.000000000000002
x =
 [5.22222222 7.66666667]
status: solved

--- System 2 ---
A =
 [[-9.  4.]
 [-6. -9.]]
b =
 [ 1. 10.]
det(A) = 105.00000000000006
x =
 [-0.46666667 -0.8       ]
status: solved



### Exercise: compute Eigendecomposition using Python numpy

Eigendecomposition is a matrix factorization method in which a square matrix is factored (decomposed) into three multiplicative matrices. Such factorization is called eigendecomposition because the entries of the matrices are eigenvalues and eigenvectors of the original square matrix. Mathematically, a square matrix A can be factored into three matrices such that: A = PDP<sup>-1</sup>

where P is the matrix of the eigenvectors of A, D is a diagonal matrix whose nonzero elements are the ordered eigenvalues of the matrix, and P<sup>-1</sup> is the inverse of the matrix P.

In [6]:
import numpy as np


# create a 2x2 matrix
matrix_2x2 = np.array([[4 ,1], [2, 3]])

# step 1: Compute the eigenvalues and eigenvectors with NumPy
eigenvalues, eigenvectors = np.linalg.eig(matrix_2x2)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# step 2: Extract the  eigenvector and the inverse of the eigenvector
V = eigenvectors
V_inverse = np.linalg.inv(V)

print("Inverse of Matrix (eigenvectors):\n", V_inverse)

#step 3: Verify the diagonalization property A = VDV⁻¹ 
D = np.diag(eigenvalues)

# Reconstruct the original matrix A using the diagonalization property
A_reconstructed = V @ D @ V_inverse
print("Diagonal matrix D:\n", D)
print("VDV⁻¹:\n", A_reconstructed)
print("Original matrix A:\n", matrix_2x2)
is_diagonalized = np.allclose(A_reconstructed, matrix_2x2)
print("Is A = VDV⁻¹?", is_diagonalized)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
Inverse of Matrix (eigenvectors):
 [[ 0.94280904  0.47140452]
 [-0.74535599  0.74535599]]
Diagonal matrix D:
 [[5. 0.]
 [0. 2.]]
VDV⁻¹:
 [[4. 1.]
 [2. 3.]]
Original matrix A:
 [[4 1]
 [2 3]]
Is A = VDV⁻¹? True


### Projection exercise

In [7]:
# import the Fraction class from the fractions module to display the results as fractions
from fractions import Fraction
np.set_printoptions(
    formatter={'all': lambda x: str(Fraction(x).limit_denominator())}
)
# create a 2x2 matrix
a = np.array([[2,1],[1,2]])
a_transpose = a.T
print("a:\n", a)
print("Transpose of a:\n", a_transpose)

# compute aᵀ·a
b = a_transpose @ a
print("aᵀ·a:\n", b)

# compute the inverse of aᵀ·a
b_inverse = np.linalg.inv(b)
print("Inverse of aᵀ·a:\n", b_inverse)

# compute the projection matrix onto the column space of a using the formula: P = A(AᵀA)⁻¹Aᵀ
proj_a = a @ b_inverse @ a_transpose
print("Projection matrix onto the column space of a:\n", proj_a)



a:
 [[2 1]
 [1 2]]
Transpose of a:
 [[2 1]
 [1 2]]
aᵀ·a:
 [[5 4]
 [4 5]]
Inverse of aᵀ·a:
 [[5/9 -4/9]
 [-4/9 5/9]]
Projection matrix onto the column space of a:
 [[1 0]
 [0 1]]


In [9]:
# Use that projection matrix to project the vector [3, 1] onto the column space of a
vector = np.array([[3], [1]])
projected_vector = proj_a @ vector
print("Projection of the vector [3, 1] onto the column space of a:\n", projected_vector)


Projection of the vector [3, 1] onto the column space of a:
 [[3]
 [1]]
