## Implement Gram-Schmidt in Python, compute orthonormal bases

In [1]:
# Exercise 1: Check orthogonality and build an orthonormal basis
import numpy as np

# Define the vectors 
v1 = np.array([1, 1, 1], dtype=float)
v2 = np.array([1, 0, 1], dtype=float)
v3 = np.array([0, 1, 0], dtype=float)

# Check if the vectors are orthogonal
def are_orthogonal(vec1, vec2):
    return np.dot(vec1, vec2) == 0 
print("v1 and v2 are orthogonal:", are_orthogonal(v1, v2))
print("v1 and v3 are orthogonal:", are_orthogonal(v1, v3))
print("v2 and v3 are orthogonal:", are_orthogonal(v2, v3))

# apply Gram-Schmidt process to build an orthonormal basis
def gram_schmidt(vectors):
    orthonormal_basis = []
    for v in vectors:
        w = v.copy()
        for u in orthonormal_basis:
            w -= np.dot(w, u) * u
        w /= np.linalg.norm(w)
        orthonormal_basis.append(w)
    return orthonormal_basis
vectors = [v1, v2, v3]
orthonormal_basis = gram_schmidt(vectors)
print("Orthonormal basis:")
for vec in orthonormal_basis:    print(vec)


v1 and v2 are orthogonal: False
v1 and v3 are orthogonal: False
v2 and v3 are orthogonal: True
Orthonormal basis:
[0.57735027 0.57735027 0.57735027]
[ 0.40824829 -0.81649658  0.40824829]
[-0.53916387 -0.64699664 -0.53916387]


In [2]:
print(v1 @ v2)  # Should be 0 for orthogonal vectors
print(v1 @ v3)  # Should be 0 for orthogonal vectors    

2.0
1.0


### QR decomposition using the Gram Schmidt process

QR decomposition is the matrix factorization technique that decomposes matrix A into the product of an orthogonal matrix Q and an upper triangular matrix R

---
1. Constructing the Q matrix using the Gram Schmidt. Here we implement the Gram Schmidt process step by step, instead of using the funcition implemented before

In [23]:
# defining a 4x3 matrix A
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [1, 0, 2],
              [2, 1, 0]], dtype=float)


# extract the first column of A
v1 = A[:, 0]

# calculate the euclidean norm of v1
norm_v1 = np.linalg.norm(v1)

# normalize v1 to get the first vector of the orthonormal basis
u1 = v1 / norm_v1

# extract the second column of A
v2 = A[:, 1]

# make v2 orthogonal to u1
proj_v2_u1 = np.dot(v2, u1) * u1
v2_orthogonal = v2 - proj_v2_u1

# calculate the euclidean norm of the orthogonalized v2
norm_v2_orthogonal = np.linalg.norm(v2_orthogonal)

# normalize the orthogonalized v2 to get the second vector of the orthonormal basis
u2 = v2_orthogonal / norm_v2_orthogonal

print(u1@u2)  # Should be 0 for orthogonal vectors

-3.246450213030829e-16


2. Constructing the R 

Now that we have our Q matrix, we need to construct the R matrix. The R matrix in QR decomposition contains information about the relationships between the columns of the orthogonal matrix Q and the original dataset. It is an upper triangular matrix, and each element of the upper triangular part of R is obtained by calculating the dot product of the corresponding columns of Q and the original data.

To construct the upper triangular matrix R, we need to calculate the dot products of each column of Q with each column of the original dataset. This will result in a matrix that has the same number of rows as the number of columns in Q, and it will be upper triangular due to our previous process.

In [24]:
Q = np.column_stack((u1, u2))
print("Orthonormal basis (columns of Q):")
print(Q)

R = Q.T @ A
print("Upper triangular matrix R:")
print(R)

# test the decomposition
A_reconstructed = Q @ R
print("Reconstructed A:")
print(A_reconstructed)

Orthonormal basis (columns of Q):
[[ 0.40824829  0.73029674]
 [ 0.          0.54772256]
 [ 0.40824829 -0.36514837]
 [ 0.81649658 -0.18257419]]
Upper triangular matrix R:
[[ 2.44948974e+00  1.63299316e+00  2.04124145e+00]
 [-7.21644966e-16  1.82574186e+00  3.65148372e+00]]
Reconstructed A:
[[ 1.00000000e+00  2.00000000e+00  3.50000000e+00]
 [-3.95261226e-16  1.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  1.38175153e-16 -5.00000000e-01]
 [ 2.00000000e+00  1.00000000e+00  1.00000000e+00]]
