In [6]:
import numpy as np

M1 = np.array([[1,1,1],[1,2,4],[1,3,9],[1,4,16],[1,5,25],[1,6,36],[1,7,49],[1,8,64],[1,9,81],[1,10,100]])
M2 = M1.transpose()

M2

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [5]:
print(M1)

[[  1   1   1]
 [  1   2   4]
 [  1   3   9]
 [  1   4  16]
 [  1   5  25]
 [  1   6  36]
 [  1   7  49]
 [  1   8  64]
 [  1   9  81]
 [  1  10 100]]


In [ ]:
M3 = M1.dot(M2)  
print(M3